### ISSUE TITLE
Upload speed

### ISSUE THREAD

**Issue by camjac251** [uhthomas/kipp#4]
This is one neat app. It's so simple but very modern. I haven't tried myself but do you use different nginx settings on your personal machine? I'm experiencing a speed issue. I'm testing over nginx from my home computer using sharex and it jumps from 30MB/s at the start to 16MB/s and then goes up and down. It never stays consistently at the top. Could this be due to the nginx?

**Comment by uhthomas** [comment]
Hey, thanks for your interest in Kipp 😄I tested the upload speed locally, and I get almost 100MB/s
```
curl --insecure https://127.0.0.1:1337 -F file=@/dev/urandom > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4048M    0     0    0 4048M      0  93.1M --:--:--  0:00:43 --:--:-- 86.6M
```

Are you referring to the [live instance](https://kipp.6f.io), or a local instance? [kipp.6f.io](https://kipp.6f.io) sits behind Cloudflare so it could be something strange going on either between `client -> cloudflare`, or `cloudflare -> kipp`.

**Comment by camjac251** [comment]
Oh hey you responded as I was editing the first post. I'm running a local instance on a Linode vps. It's just running on a test domain behind nginx using the sample config. I attempted to upload a 5GB file and it completed the upload but hasn't generated the url yet.

**Comment by camjac251** [comment]
I must have a bad system here. Running curl locally I get
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  725M    0     0    0  725M      0  42.2M --:--:--  0:00:17 --:--:-- 41.3M
```

**Comment by uhthomas** [comment]
Interesting. The service isn't all that complicated, so I don't really understand there would be any significant performance impacts, or why a slug wouldn't be generated. [kipp.6f.io](https://kipp.6f.io) is also running on a Linode VPS.

Can you check the directory where the uploaded files are being persisted to?

**Comment by camjac251** [comment]
I took a few shortcuts for simplicity sake. I'm just using this to test but I made a directory /kipp and changed nginx to run as root and go commands as root.

**Comment by camjac251** [comment]
It shouldn't be slow because of how I'm running it right? I'm on Debian 10 now with a Linode standard 2GB instance now and got a little faster of a result, 53.9M. I'll try creating a file first and uploading that

**Comment by uhthomas** [comment]
Are you running it in Docker? The only thing the server is doing whilst uploading is hashing the steam using blake2b. However, it has SIMB optimisation so shouldn't be slow at all.

**Comment by camjac251** [comment]
No docker. Just used the first block in the readme

**Comment by camjac251** [comment]
I tested curl with a PHP host to see if I got the same speed. It was outputting 400MB/s for this
`curl http://127.0.0.1/upload -F "token=token_a17f5f84a7e40d82c1074b392a92bb98" -F upload=@thiscooliamge.avi > /dev/null`
Could there be a difference in my config to yours or maybe different go versions? I wonder if Go isn't running as fast as it should

**Comment by uhthomas** [comment]
It does seem weird. The benchmarks for [`blake2b-simd`](https://github.com/minio/blake2b-simd) seem fine.

It could TLS being slow... I'll investigate a little and get back to you. For the time being, 16MB/s (128mbps) should be sufficient.

I'm working on refactoring the code a little too, so I'll add some benchmarks and we can really understand what's going on.

**Comment by camjac251** [comment]
I really like Go. Have you tried kripp with larger file transfers? I was hoping to find something that could service really large files at fast rates (as a cheaper option to massive.io).

**Comment by uhthomas** [comment]
It's funny you mention that. Kipp isn't really designed for massive files, although there's no reason it shouldn't have a problem with them.

However I have a project, [palladium](https://palladium.dev/) which is designed specifically for transferring large, end-to-end encrypted files. So, stay on the lookout for that.

Don't worry 😅The service uses [io.Copy](https://golang.org/pkg/io/#Copy), so it only used 32kb of memory to upload files.

**Comment by camjac251** [comment]
I can't wait to see palladium. Will this be a browser based tool, CLI, GUI? With palladium, will it require both parties to be present if it's E2E?

**Comment by uhthomas** [comment]
It will be designed for browsers, as it's the most accessible medium, but there will be CLIs and mobile apps. It uses IPFS, and will act as a pinning service. This means that you can either stream files peer-to-peer, or share a permanent link which proxies the encrypted content through the service.

**Comment by camjac251** [comment]
Do you know when an alpha will be available for palladium?

**Comment by uhthomas** [comment]
I don't have any dates, but hopefully within the next few months. Pretty busy with work and other projects at the moment too 😄

**Comment by camjac251** [comment]
Ok cool. I got a bit excited seeing `The project is currently under development - there should be a beta out sometime late March or early April.`

**Comment by uhthomas** [comment]
I have a lot of faith in Palladium so I would like to see it done soon 😄 

I've been working on kipp a little bit since this issue was opened, and there are a few key things to note:
* The default database has changed from boltdb to badger
* The checksum algorithm has changed from blake2b to blake3
* The project has been reorganised to be testable, scalable and interoperable. This essentially means the service now supports any database (badger, psql, scylla, etc.) you can imagine as long as it implements the interface, and it now supports any file system (local, s3, backblaze, etc.).
* The service has dropped TLS support for the time-being, as it should be running behind proxies anyway.

Hopefully these changes make the service more attractive and provide more options for individual environments. I'd be interested to see if there's any change in performance, but I have a feeling there's something more going on...

There are some more things I intend to add / change, but these are the main big ones which make the path for the upcoming stuff.

**Comment by uhthomas** [comment]
If you're interested in trying it out then the easiest way would be to use the [docker image on docker hub](https://hub.docker.com/layers/uhthomas/kipp/latest/images/sha256-1e332f22af5c9c9dff9b71bb72699377efe936ceeabcb67b7abe4868143322bf?context=repo).

**Comment by camjac251** [comment]
Oh wow, this is great. I will definitely setup an instance of this. The amount of work you put in to this in the little time is incredible

**Comment by camjac251** [comment]
Would setting this up over Go directly instead of using Docker offer higher performance, less resource usage?

**Comment by uhthomas** [comment]
Thank you 😄 

The difference in resource usage would be negligible I imagine.

**Comment by camjac251** [comment]
Does kipp use any chunked uploading function? I was thinking about solving a speed problem that might happen with Cloudflare but their `HTTP POST` request size is maxed at 100MB for free and pro members. If uploads were chunked in say 50MB (or maybe based on a quick speedtest done on the user before an upload happens, maybe half the value of their upload speed) then it could allow for CloudFlare to proxy the connection and hopefully increase speed, but also maybe achieve the absolute max upload speed if the chunks were threaded.
https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN

**Comment by uhthomas** [comment]
So, kipp performs the same way as any other HTTP server - it reads the request body in chunks of 32KB. It's an interesting idea, and I think some services do use this technique (for file resumption) - but it would actually decrease the speed due to the overhead of establishing new connections.

The meat of the upload code can be found [here](https://github.com/uhthomas/kipp/blob/master/server.go#L201-L206), and there's not all that much going on so I would assume that any performance degradation would be due to the underlying filesystem. Happy to look into it more though if you do find some issues.

**Comment by uhthomas** [comment]
Just wanted to report that I'm running the current version of `master` on [dev.kipp.6f.io](http://dev.kipp.6f.io) and I just ran the same test as before. Here's the results:
```
$ curl https://dev.kipp.6f.io -F file=@/dev/zero > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  150M  100   176    0  150M    140   120M  0:00:01  0:00:01 --:--:--  120M
```

I encourage you to try the same thing - it looks like I'm getting 120MB/s (960mbps!).

**Comment by bezo97** [comment]
I run the above test and got the following results:
```
$ curl https://dev.kipp.6f.io -F file=@/dev/zero | tee /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  150M  100   176    0  150M      1  1734k  0:02:56  0:01:28  0:01:28 1731k
```

**Comment by uhthomas** [comment]
that's atrocious - I wonder if it has anything to do with geo-location. The server is hosted in London, so it could be something weird happening there. I'll turn on Cloudflare for this domain and see if it helps at all.

**Comment by uhthomas** [comment]
I'm going to close this for now as I'm pretty confident there are no issues with the upload speed. Please feel free to re-open if you don't think this is the case, or create a new issue if you have any other questions 😄
